---
title: "sapflow-Rs"
author: "SP"
date: "9/10/2019"
output: html_document
---

##Prelim plots to make:
* figure out how to calculate Js
* table with no of datapoints
* available time periods
* need table with Js, table with Rs, climate data
* then add all to one dataframe on common time frame
* TOD facet by month, Js/Rs lines

```{r functions, echo = FALSE, message = FALSE}
# Load functions
library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(viridis)

```

```{r load-data, echo = FALSE, message = FALSE}
# Load in Rs, K, weather, and inventory data
inventory <- read_csv("../../PREMIS-stormsurge/inventory/ss-inventory.csv")
ports_lt <- read_csv("../../PREMIS-ghg/design/LT_portcodes.csv")
species_codes <- read_csv("../../PREMIS-ghg/inventory_data/species_codes.csv")

read_csv("../SERC/baseliner_data/control_Kest_yr.csv", 
         col_names = c("Year", "DOY","Time","VPD", "PAR", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8")) %>% 
  mutate(Date = as_date(DOY - 1, origin = "2018-01-01")) %>% 
  separate(Date, c("Y", "Month", "Day"), sep = "-") %>% 
  separate(Time, c("Hour", "Min"), sep = -2) -> control_hm
  
control_hm$Hour[control_hm$Hour == ""] <- 0

control_hm %>% 
  mutate(Timestamp = mdy_hm(paste0(Month, "-", Day, "-", Year, " ", Hour, ":", Min))) %>%
  select(-Y, -Year, - Day, - Month) %>% 
  gather("Tree", "K", C1:C8) %>% 
  left_join(inventory, by = c("Tree" = "Sapflux")) %>% 
  select(Timestamp, VPD, PAR, K, Tree, Species_code, Plot) -> control_long

read_csv("../SERC/con_licor_data_20191120.csv") %>%
  left_join(ports_lt, by = "Port") %>% 
  left_join(inventory, by = c("Tree" = "Sapflux"))-> rs_long

# Load weather data
read_csv("../SERC/met_data/SECPRE_30min.csv") %>% 
  mutate(Timestamp = ymd_hms(endDateTime)) %>% 
  rename(Precip = secPrecipBulk) %>% 
  select(Timestamp, Precip) -> precip

read_csv("../SERC/met_data/RH_30min.csv") %>% 
  mutate(Timestamp = ymd_hms(endDateTime)) %>% 
  rename(RH = RHMean, Temp = tempRHMean) %>% 
  select(Timestamp, RH, Temp) %>% 
  left_join(precip, by = "Timestamp") -> wx_dat

```

```{r data-cleaning, echo = FALSE, message = FALSE}
# Next, we need to filter for the Js trees that also have Rs measurements
rs_trees <- unique(ports_lt$Tree)
sunrise <- 6
sunset <- 19

control_long %>% 
  #Then, we need to transform K to Js (sapflux density) through a conversion
  mutate(Js = 119* 10^(-4) * K^(1.231)) %>% 
  filter(Tree %in% rs_trees) %>% 
  # Then, we need to round the timestamp to the nearest hour and take hourly averages
  mutate(Timestamp = round_date(Timestamp, unit = "hour")) %>% 
  # Now that all data are on a common timeframe, we can take the hourly mean of each dataset
  group_by(Timestamp, Tree, Species_code) %>% 
  summarise(Js_avg = mean(Js)) -> control_filter

rs_long %>%
  filter(Flux > 0, Flux < 25) %>%
  mutate(Timestamp = round_date(Timestamp, unit = "hour")) %>%
  group_by(Timestamp, Species_code) %>%
  summarise(rs_avg = mean(Flux)) -> rs_filter

control_filter %>% 
  left_join(rs_filter) %>% 
  na.omit() %>% 
  semi_join(wx_dat) -> combined

combined %>% 
  mutate(Hour = hour(Timestamp)) %>% 
  group_by(Hour, Species_code) %>% 
  summarise(rs_havg = mean(rs_avg), Js_havg = mean(Js_avg)) %>% 
  mutate(Daytime = if_else(Hour > sunrise & Hour < sunset, TRUE, FALSE)) %>% 
  left_join(species_codes) -> hourly

gather(hourly, key = "Type", value = "Value", rs_havg:Js_havg) -> hourly_long

```

```{r hour-of-day}
rs_min <- 7
rs_max <- 11
hourly_long[which(hourly_long$Type == "Js_havg"), ] -> x

hourly_long %>% 
  ungroup %>% 
  filter(Type == "Js_havg") %>% 
  select(-Value) %>% 
  mutate(Value  = (rs_max - rs_min) * ((x$Value - min(x$Value))/(max(x$Value) - min(x$Value))) + rs_min) -> hourly_check

hourly_long %>% 
  filter(Type == "rs_havg") %>% 
  bind_rows(hourly_check) -> hourly_norm

ggplot(filter(hourly_norm), aes(x = Hour, y = Value, color = Type, group = Type)) +
  geom_line() +
  geom_point(size = 1) +
  scale_color_viridis(discrete = TRUE, 
                      option = "D", 
                      begin =0.7, 
                      end = 0.4,
                      labels = c("Js", "Rs")) +
  labs(x = "Hour of Day", y = "Value") +
  facet_wrap(~Species) + 
  theme_minimal() +
  theme(strip.text.x = element_text(face = "bold.italic", size = 12)) 
  
```

```{r rs-js}
ggplot(hourly, aes(x = Js_havg, rs_havg)) +
  geom_point(aes(color = Daytime)) +
  geom_smooth(aes(group = Daytime, color = Daytime, fill = Daytime), method = "lm") +
  scale_color_viridis(discrete = TRUE,
                      name = "Time of Day",
                      labels = c("Nighttime", "Daytime")) +
  scale_fill_viridis(discrete = TRUE,
                     name = "Time of Day",
                     labels = c("Nighttime", "Daytime")) +
  labs(x = "Js (cm/s)", y = "Rs (umol/m/s)") +
  theme_minimal()
```


Number of Js obs: `r nrow(combined)`
Number of Rs obs: `r nrow(combined)`


